In [15]:
import math
import numpy as np
from typing import List

### Construct a matrix using nested array without numpy

In [2]:
matrix: List[int] = [[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]]

In [3]:
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

### Every element being added 1 when using pure nested array

In [5]:
[[i + 1 for i in row] for row in matrix]

[[2, 3, 4], [5, 6, 7], [8, 9, 10]]

# Constructing an array using NumPy

In [6]:
array1 = np.array([10, 100, 1_000])
array2 = np.array([[1, 2, 3],
                   [4, 5, 6]])

In [7]:
array1

array([  10,  100, 1000])

In [8]:
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
array1.dtype

dtype('int64')

## Vectorisation & Broadcasting

### Broadcasting

In [11]:
array2 + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [12]:
array2 * array2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [13]:
array2 * array1

array([[  10,  200, 3000],
       [  40,  500, 6000]])

### Matrix multiplication or inner product

In [14]:
array2 @ array2.T

array([[14, 32],
       [32, 77]])

## Using NumPy ufunc

In [16]:
try:
    math.sqrt(array2)
except TypeError as e:
    print(e)

only length-1 arrays can be converted to Python scalars


In [17]:
np.array([[math.sqrt(i) for i in row] for row in array2])

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [18]:
# By NumPy ufunc
np.sqrt(array2)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [22]:
array2.sum(axis=0)  # sum up all the elements with same columns but different rows

array([5, 7, 9])

In [23]:
array2.sum(axis=1)  # sum up all the elements with same rows but different columns

array([ 6, 15])

In [25]:
array2.sum()  # sum every element up to return a number

21

## Accessing elements

In [29]:
# Chained Indexing when pure nested array
matrix[0][2]

3

### numpy_array[selection] when using NumPy

In [35]:
array1

array([  10,  100, 1000])

In [36]:
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
array1[2]

1000

In [38]:
array2[0, 0]

1

In [39]:
array2[:, 1:]

array([[2, 3],
       [5, 6]])

In [40]:
array2[:, 1]

array([2, 5])

In [41]:
array2[1, :2]

array([4, 5])

## Initiate NumPy instance

In [42]:
# 10 items, 2 rows, 5 columns
np.arange(2 * 5).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [43]:
# randomly generate 6 floating numbers, 2 rows, 3 columns
np.random.randn(2, 3)

array([[ 0.75855423, -0.32264011, -0.59893788],
       [-0.86205506,  0.86234372, -1.78431642]])

## Views & Copy

In [45]:
# Get views by slicing
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
subset = array2[:, :2]
subset

array([[1, 2],
       [4, 5]])

In [47]:
subset[0, 0] = 1_000
subset

array([[1000,    2],
       [   4,    5]])

In [48]:
array2

array([[1000,    2,    3],
       [   4,    5,    6]])

In [49]:
# Get copy
array2

array([[1000,    2,    3],
       [   4,    5,    6]])

In [50]:
subset = array2[:, :2].copy()
subset

array([[1000,    2],
       [   4,    5]])

In [51]:
subset[0, 0] = 1
subset

array([[1, 2],
       [4, 5]])

In [52]:
array2

array([[1000,    2,    3],
       [   4,    5,    6]])